### ISSUE TITLE
rozważania nad czasami

### ISSUE THREAD

**Issue by mmagnuski** [mmagnuski/LinOrd#4]
Tutaj porozważamy czasy prezentacji aby prestim było odpowiednie do planowanych analiz.

**Comment by mmagnuski** [comment]
Obecnie czasy są takie:

``` yaml
times:
   pre_pair: [0.6, 1.2]
   element: 0.75
   before_relation: 0.25
   relation: 0.75
   after_relation: 0.25
   after_pair: [0.6, 1.2]
   after_last_pair: [4.5, 5.5]
   after_last_question: [1.5, 2.5]
   fix_highlights: [0.5, 1.]
   pre_question_mark: 0.1
   question_mark: 0.2
   response: 5
```

ale z tego co pamiętam nie wszystko jest z myślą o sekwencyjnej prezentacji.
To trzeba będzie jeszcze ugładzić.
